services:
  - type: web
    name: yellow-track-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: node src/server.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: UPLOAD_DIR
        value: ./uploads
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://yellow-track-git-main-eswarprasadofficial-6122s-projects.vercel.app,https://yellow-track-8ba2kpydj-eswarprasadofficial-6122s-projects.vercel.app
